// AUTH REDUCER TYPES
export const TEST_TYPE = 'TEST_TYPE'
// REDDIT REDUCER TYPES
export const GET_POSTS = 'GET_POSTS'
export const SET_SUBREDDIT = 'SET_SUBREDDIT'
export const GET_DEFAULT_SUBREDDITS = 'GET_DEFAULT_SUBREDDITS'
export const SET_LOADING = 'SET_LOADING'
export const CHANGE_SORT_BY = 'CHANGE_SORT_BY'
